In [1]:
import pandas as pd

In [2]:
# importing the dataset
data=pd.read_csv("data.csv")

In [3]:
data

,student_id,age,gender,course_type,session_count,avg_session_duration,quiz_attempts,assignments_submitted,satisfaction_rating,dropout
0,S0001,24,Male,UI/UX,11,108.13,7,5,5,0
1,S0002,37,Male,Python,9,59.51,3,1,1,1
2,S0003,32,Male,UI/UX,15,81.77,3,3,1,1
3,S0004,28,Female,Digital Marketing,7,24.82,4,4,1,1
4,S0005,25,Female,Digital Marketing,5,27.11,7,1,4,1
...,...,...,...,...,...,...,...,...,...,...
195,S0196,19,Female,Python,3,113.94,5,1,1,1
196,S0197,38,Female,UI/UX,7,22.64,1,5,4,1
197,S0198,29,Female,UI/UX,3,72.42,0,4,4,1
198,S0199,23,Other,Digital Marketing,23,63.18,4,0,5,0
199,S0200,21,Other,UI/UX,24,75.32,8,0,5,0

In [5]:
# checking for unique value in course_type column
data['course_type'].unique()

array(['UI/UX', 'Python', 'Digital Marketing'], dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le=LabelEncoder()

In [8]:
#encoding the object into int type
data['course_type']=le.fit_transform(data['course_type'])

In [9]:
data['course_type']

0      2
1      1
2      2
3      0
4      0
      ..
195    1
196    2
197    2
198    0
199    2
Name: course_type, Length: 200, dtype: int64

In [10]:
data

,student_id,age,gender,course_type,session_count,avg_session_duration,quiz_attempts,assignments_submitted,satisfaction_rating,dropout
0,S0001,24,Male,2,11,108.13,7,5,5,0
1,S0002,37,Male,1,9,59.51,3,1,1,1
2,S0003,32,Male,2,15,81.77,3,3,1,1
3,S0004,28,Female,0,7,24.82,4,4,1,1
4,S0005,25,Female,0,5,27.11,7,1,4,1
...,...,...,...,...,...,...,...,...,...,...
195,S0196,19,Female,1,3,113.94,5,1,1,1
196,S0197,38,Female,2,7,22.64,1,5,4,1
197,S0198,29,Female,2,3,72.42,0,4,4,1
198,S0199,23,Other,0,23,63.18,4,0,5,0
199,S0200,21,Other,2,24,75.32,8,0,5,0

In [11]:
# checking for unique value in gender column
data['gender'].unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [12]:
#encoding the object into int type
data['gender']=le.fit_transform(data['gender'])

In [13]:
data

,student_id,age,gender,course_type,session_count,avg_session_duration,quiz_attempts,assignments_submitted,satisfaction_rating,dropout
0,S0001,24,1,2,11,108.13,7,5,5,0
1,S0002,37,1,1,9,59.51,3,1,1,1
2,S0003,32,1,2,15,81.77,3,3,1,1
3,S0004,28,0,0,7,24.82,4,4,1,1
4,S0005,25,0,0,5,27.11,7,1,4,1
...,...,...,...,...,...,...,...,...,...,...
195,S0196,19,0,1,3,113.94,5,1,1,1
196,S0197,38,0,2,7,22.64,1,5,4,1
197,S0198,29,0,2,3,72.42,0,4,4,1
198,S0199,23,2,0,23,63.18,4,0,5,0
199,S0200,21,2,2,24,75.32,8,0,5,0

In [15]:
data.dtypes

student_id                object
age                        int64
gender                     int64
course_type                int64
session_count              int64
avg_session_duration     float64
quiz_attempts              int64
assignments_submitted      int64
satisfaction_rating        int64
dropout                    int64
dtype: object

In [16]:
# dropping the student_id column
data.drop(["student_id"],axis=1,inplace=True)

In [17]:
data

,age,gender,course_type,session_count,avg_session_duration,quiz_attempts,assignments_submitted,satisfaction_rating,dropout
0,24,1,2,11,108.13,7,5,5,0
1,37,1,1,9,59.51,3,1,1,1
2,32,1,2,15,81.77,3,3,1,1
3,28,0,0,7,24.82,4,4,1,1
4,25,0,0,5,27.11,7,1,4,1
...,...,...,...,...,...,...,...,...,...
195,19,0,1,3,113.94,5,1,1,1
196,38,0,2,7,22.64,1,5,4,1
197,29,0,2,3,72.42,0,4,4,1
198,23,2,0,23,63.18,4,0,5,0
199,21,2,2,24,75.32,8,0,5,0

In [18]:
#checking for null values
data.isnull().sum()

age                      0
gender                   0
course_type              0
session_count            0
avg_session_duration     0
quiz_attempts            0
assignments_submitted    0
satisfaction_rating      0
dropout                  0
dtype: int64

In [19]:
data.describe()

,age,gender,course_type,session_count,avg_session_duration,quiz_attempts,assignments_submitted,satisfaction_rating,dropout
count,200.000000,200.000000,200.00000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,27.850000,0.720000,0.90500,14.415000,59.160200,4.320000,2.380000,3.090000,0.485000
std,6.422127,0.673698,0.85418,8.898804,31.797223,2.865073,1.720582,1.411332,0.501029
min,18.000000,0.000000,0.00000,0.000000,7.310000,0.000000,0.000000,1.000000,0.000000
25%,22.000000,0.000000,0.00000,6.750000,30.850000,2.000000,1.000000,2.000000,0.000000
50%,27.500000,1.000000,1.00000,15.000000,58.160000,4.000000,2.000000,3.000000,0.000000
75%,33.000000,1.000000,2.00000,22.000000,87.230000,7.000000,4.000000,4.000000,1.000000
max,39.000000,2.000000,2.00000,29.000000,118.850000,9.000000,5.000000,5.000000,1.000000

In [24]:
# assigning the columns for x and y variable
x=data.drop(["dropout"],axis=1)
y=data["dropout"]

In [25]:
# splitting the dataset
from sklearn.model_selection import train_test_split
xtrian,xtest,ytrain,ytest=train_test_split(x,y,random_state=1,test_size=0.3)

In [20]:
import tensorflow as tf

In [21]:
from tensorflow import keras

In [27]:
# creating the model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=64, activation='relu', input_shape=(8,)),
    tf.keras.layers.Dense(units=32, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(units=32, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(units=32, activation='relu'),
    tf.keras.layers.Dense(units=1) # Output layer for linear regression (no activation)
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [28]:
# Compile the model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [29]:
# fitting the model on the train dataset
model.fit(xtrian,ytrain,epochs=50,batch_size=32,validation_data=(xtest,ytest))

Epoch 1/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 94ms/step - loss: 88.7647 - mae: 6.8216 - val_loss: 3.1689 - val_mae: 1.4241
Epoch 2/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 42.0679 - mae: 4.9888 - val_loss: 2.0355 - val_mae: 1.1757
Epoch 3/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 30.9471 - mae: 3.9770 - val_loss: 1.3629 - val_mae: 0.9951
Epoch 4/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 15.0198 - mae: 2.8459 - val_loss: 1.0063 - val_mae: 0.8718
Epoch 5/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 7.1866 - mae: 2.1120 - val_loss: 0.7001 - val_mae: 0.6882
Epoch 6/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 7.0139 - mae: 1.8761 - val_loss: 0.4410 - val_mae: 0.5312
Epoch 7/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 3.9931 - mae: 1.4576 - val_loss: 0.3332 - val_mae: 0.4819
Epoch 8/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 6.5238 - mae: 1.7714 - val_loss: 0.3219 - val_mae: 0.4796
Epoch 9/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 3.0448 - mae: 1.2910 - val_loss: 0.3163 - val_mae: 0.4806
Epoch 10/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 3.4938 - mae: 1.3452 - val_loss: 0.3131 - val_mae: 0.4843
Epoch 11/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 2.4343 - mae: 1.1856 - val_loss: 0.3120 - val_mae: 0.4891
Epoch 12/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.6447 - mae: 0.9928 - val_loss: 0.3106 - val_mae: 0.4927
Epoch 13/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1.1399 - mae: 0.8456 - val_loss: 0.3094 - val_mae: 0.4956
Epoch 14/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1.5629 - mae: 0.9687 - val_loss: 0.3098 - val_mae: 0.4986
Epoch 15/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 1.3882 - mae: 0.8811 - val_loss: 0.3102 - val_mae: 0.5018
Epoch 16/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 1.2073 - mae: 0.8555 - val_loss: 0.3125 - val_mae: 0.5049
Epoch 17/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 1.0234 - mae: 0.8018 - val_loss: 0.3190 - val_mae: 0.5073
Epoch 18/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1.6241 - mae: 0.8774 - val_loss: 0.3234 - val_mae: 0.5083
Epoch 19/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.8910 - mae: 0.7103 - val_loss: 0.3233 - val_mae: 0.5087
Epoch 20/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 1.3409 - mae: 0.8821 - val_loss: 0.3208 - val_mae: 0.5091
Epoch 21/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.7813 - mae: 0.6981 - val_loss: 0.3206 - val_mae: 0.5100
Epoch 22/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.7071 - mae: 0.6576 - val_loss: 0.3182 - val_mae: 0.5098
Epoch 23/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.9053 - mae: 0.7436 - val_loss: 0.3176 - val_mae: 0.5101
Epoch 24/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.6582 - mae: 0.6613 - val_loss: 0.3152 - val_mae: 0.5093
Epoch 25/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.7443 - mae: 0.6683 - val_loss: 0.3128 - val_mae: 0.5078
Epoch 26/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.6997 - mae: 0.6282 - val_loss: 0.3107 - val_mae: 0.5071
Epoch 27/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.8286 - mae: 0.6921 - val_loss: 0.3098 - val_mae: 0.5070
Epoch 28/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.5530 - mae: 0.6072 - val_loss: 0.3067 - val_mae: 0.5067
Epoch 29/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.7809 - mae: 0.6653 - val_loss: 0.3057 - val_mae: 0.5072
Epoch 30/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.7100 - mae: 0.6588 - val_loss: 0.3052 - val_mae: 0.5073
Epoch 31/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.5463 - mae: 0.5750 - val_loss: 0.3026 - val_mae: 0.5062
Epoch 32/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.6119 - mae: 0.5804 - val_loss: 0.3017 - val_mae: 0.5056
Epoch 33/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.6928 - mae: 0.6328 - val_loss: 0.3021 - val_mae: 0.5045
Epoch 34/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.4744 - mae: 0.5399 - val_loss: 0.3047 - val_mae: 0.5047
Epoch 35/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.4507 - mae: 0.5411 - val_loss: 0.3059 - val_mae: 0.5055
Epoch 36/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.4381 - mae: 0.5403 - val_loss: 0.3062 - val_mae: 0.5061
Epoch 37/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.3916 - mae: 0.4906 - val_loss: 0.3057 - val_mae: 0.5062
Epoch 38/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.5644 - mae: 0.5943 - val_loss: 0.3045 - val_mae: 0.5055
Epoch 39/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.4740 - mae: 0.5881 - val_loss: 0.3030 - val_mae: 0.5052
Epoch 40/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.6060 - mae: 0.6163 - val_loss: 0.3005 - val_mae: 0.5043
Epoch 41/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.5786 - mae: 0.5650 - val_loss: 0.2976 - val_mae: 0.5032
Epoch 42/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.4114 - mae: 0.5159 - val_loss: 0.2954 - val_mae: 0.5026
Epoch 43/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.4454 - mae: 0.5364 - val_loss: 0.2928 - val_mae: 0.5024
Epoch 44/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.4308 - mae: 0.5395 - val_loss: 0.2905 - val_mae: 0.5021
Epoch 45/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.4499 - mae: 0.5800 - val_loss: 0.2884 - val_mae: 0.5017
Epoch 46/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.3843 - mae: 0.5173 - val_loss: 0.2871 - val_mae: 0.5020
Epoch 47/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.4337 - mae: 0.5447 - val_loss: 0.2863 - val_mae: 0.5020
Epoch 48/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.3994 - mae: 0.5320 - val_loss: 0.2846 - val_mae: 0.5009
Epoch 49/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.3129 - mae: 0.4848 - val_loss: 0.2829 - val_mae: 0.4997
Epoch 50/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.3205 - mae: 0.4756 - val_loss: 0.2819 - val_mae: 0.4991

In [31]:
from sklearn.metrics import r2_score, mean_squared_error

predictions = model.predict(xtest)
r2 = r2_score(ytest, predictions)
mse = mean_squared_error(ytest, predictions)

# Print the results
print(f"R-squared: {r2}")
print(f"Mean Squared Error: {mse}")

2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 532ms/step
R-squared: -0.13262724876403809
Mean Squared Error: 0.2818983793258667